<a href="https://colab.research.google.com/github/haiobr/DataTwitter-Eleitoral/blob/main/Etapa_3_EDA%2C_Storytelling_e_Visualiza%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Etapa_3 - EDA, Storytelling e Visualização

In [ ]:
# Importar Pandas
import pandas as pd

# Importar RE - Expressões Regulares
import re

In [ ]:
dataframe_final = pd.read_csv("dataframe_final_candidatos.csv")

In [ ]:
dataframe_final.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-08-02 01:53:03+00:00,1554284109001801732,Partidos negam apoio a Lula e frustram planos ...,Lula
1,2022-08-02 01:53:01+00:00,1554284101359788032,@LulaOficial #LulaNoPrimeiroTurno https://t.co...,Lula
2,2022-08-02 01:53:00+00:00,1554284097035505664,@Wagner87222512 @Davi31570942 @LulaOficial @gi...,Lula
3,2022-08-02 01:53:00+00:00,1554284095336751105,@felipeneto E tanta inconpetencia que ele sosi...,Lula
4,2022-08-02 01:52:59+00:00,1554284091322793985,@Belzebu__666 @ThiagoResiste @LulaOficial Esse...,Lula

In [ ]:
# Identificar tipos dos dados
dataframe_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data_Hora  153 non-null    object
 1   IdTweet    153 non-null    int64
 2   Tweet      153 non-null    object
 3   Candidato  153 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [ ]:
# Somar todos os 'nulos', quando houver.
dataframe_final.isnull().sum()

Data_Hora    0
IdTweet      0
Tweet        0
Candidato    0
dtype: int64

In [ ]:
# Criar um coluna 'Tweet_limpo' que será a coluna final após a limpeza dos dados.
dataframe_final['Tweet_limpo'] = dataframe_final['Tweet']

In [ ]:
dataframe_final.head()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-08-02 01:53:03+00:00,1554284109001801732,Partidos negam apoio a Lula e frustram planos ...,Lula,Partidos negam apoio a Lula e frustram planos ...
1,2022-08-02 01:53:01+00:00,1554284101359788032,@LulaOficial #LulaNoPrimeiroTurno https://t.co...,Lula,@LulaOficial #LulaNoPrimeiroTurno https://t.co...
2,2022-08-02 01:53:00+00:00,1554284097035505664,@Wagner87222512 @Davi31570942 @LulaOficial @gi...,Lula,@Wagner87222512 @Davi31570942 @LulaOficial @gi...
3,2022-08-02 01:53:00+00:00,1554284095336751105,@felipeneto E tanta inconpetencia que ele sosi...,Lula,@felipeneto E tanta inconpetencia que ele sosi...
4,2022-08-02 01:52:59+00:00,1554284091322793985,@Belzebu__666 @ThiagoResiste @LulaOficial Esse...,Lula,@Belzebu__666 @ThiagoResiste @LulaOficial Esse...

In [ ]:
# Criar um função que irá realizar alguns tratamento na coluna 'Tweet' e salvar na coluna 'Tweet_Limpo'
def limpeza_do_texto(tweet):
  # Deixa todos os tweet minúsculos.
  tweet = tweet.lower()

  tweet = re.sub('\n', '', tweet)
  tweet = re.sub('@[^\s]+', '', tweet)
  tweet = re.sub('\B#\S+', '', tweet)
  tweet = re.sub('https?://\S+|www\.\S+', '', tweet)
  return tweet

In [ ]:
# Referencia a coluna origem 'Tweet' onde será aplicado a função 'limpeza_do_texto' e o resultado será gravado na coluna 'Tweet_Limpo'.
dataframe_final['Tweet_limpo'] = dataframe_final['Tweet'].apply(lambda i: limpeza_do_texto(i))

In [ ]:
dataframe_final.head()

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-08-02 01:53:03+00:00,1554284109001801732,Partidos negam apoio a Lula e frustram planos ...,Lula,partidos negam apoio a lula e frustram planos ...
1,2022-08-02 01:53:01+00:00,1554284101359788032,@LulaOficial #LulaNoPrimeiroTurno https://t.co...,Lula,
2,2022-08-02 01:53:00+00:00,1554284097035505664,@Wagner87222512 @Davi31570942 @LulaOficial @gi...,Lula,você falou tudo. 👏👏👏👏
3,2022-08-02 01:53:00+00:00,1554284095336751105,@felipeneto E tanta inconpetencia que ele sosi...,Lula,e tanta inconpetencia que ele sosinho tá derr...
4,2022-08-02 01:52:59+00:00,1554284091322793985,@Belzebu__666 @ThiagoResiste @LulaOficial Esse...,Lula,esse é f#da skskskkskssksk

In [ ]:
# Exportanto CSV
dataframe_final.to_csv('dataframe_final_candidatos_pronto_para_sentimento.csv', sep= ',', index=False)